//! Nordum word-list rules (stage 1): source-language spellings normalized to
//! the Nordum rules (spec §3.3.2 and §3.6), morphology, numerals,
//! prepositions, loanwords and the capitalization check. Data files live in
//! `data/nrd/rules/`.

use std::path::Path;

use lt_core::Result;

use crate::simple_replace::{CaseSensitivity, SimpleReplaceConfig, SimpleReplaceRule};

/// All default-on Nordum list rules, in `getRelevantRules` order.
pub fn nordum_instances(data_dir: &Path) -> Result<Vec<SimpleReplaceRule>> {
    let rules_dir = data_dir.join("nrd/rules");
    Ok(vec![
        SimpleReplaceRule::from_files(
            &[rules_dir.join("source_forms.txt")],
            SimpleReplaceConfig {
                rule_id: "NDM_SOURCE_FORMS",
                description: "Source-language spelling normalized to Nordum ($match)",
                short: "Nordum spelling",
                message:
                    "'$match' follows a source-language spelling. The Nordum form is $suggestions.",
                suggestions_separator: " or ",
                sub_rule_specific_ids: false,
                case_sensitivity: CaseSensitivity::Ci,
                category_id: "TYPOS",
                category_name: "Possible Typo",
                issue_type: "misspelling",
                default_off: false,
                picky: false,
                has_suggestions: true,
                checking_case: false,
                ignore_short_uppercase_words: true,
                is_token_exception: crate::simple_replace::TokenException::None,
            },
        )?,
        SimpleReplaceRule::from_files(
            &[rules_dir.join("morphology.txt")],
            SimpleReplaceConfig {
                rule_id: "NDM_MORPHOLOGY",
                description: "Nordum word formation ($match)",
                short: "Nordum morphology",
                message: "'$match' does not follow the Nordum paradigm. Use $suggestions.",
                suggestions_separator: " or ",
                sub_rule_specific_ids: false,
                case_sensitivity: CaseSensitivity::Ci,
                category_id: "GRAMMAR",
                category_name: "Grammar",
                issue_type: "grammar",
                default_off: false,
                picky: false,
                has_suggestions: true,
                checking_case: false,
                ignore_short_uppercase_words: true,
                is_token_exception: crate::simple_replace::TokenException::None,
            },
        )?,
        SimpleReplaceRule::from_files(
            &[rules_dir.join("compounds.txt")],
            SimpleReplaceConfig {
                rule_id: "NDM_COMPOUND",
                description: "Compound spelling ($match)",
                short: "Compound",
                message: "'$match' must be written as one word: $suggestions.",
                suggestions_separator: " or ",
                sub_rule_specific_ids: false,
                case_sensitivity: CaseSensitivity::Ci,
                category_id: "TYPOS",
                category_name: "Possible Typo",
                issue_type: "misspelling",
                default_off: false,
                picky: false,
                has_suggestions: true,
                checking_case: false,
                ignore_short_uppercase_words: true,
                is_token_exception: crate::simple_replace::TokenException::None,
            },
        )?,
        SimpleReplaceRule::from_files(
            &[rules_dir.join("numerals.txt")],
            SimpleReplaceConfig {
                rule_id: "NDM_NUMERALS",
                description: "Nordum numerals ($match)",
                short: "Numeral",
                message: "'$match' is a source-language numeral. In Nordum: $suggestions.",
                suggestions_separator: " or ",
                sub_rule_specific_ids: false,
                case_sensitivity: CaseSensitivity::Ci,
                category_id: "GRAMMAR",
                category_name: "Grammar",
                issue_type: "grammar",
                default_off: false,
                picky: false,
                has_suggestions: true,
                checking_case: false,
                ignore_short_uppercase_words: true,
                is_token_exception: crate::simple_replace::TokenException::None,
            },
        )?,
        SimpleReplaceRule::from_files(
            &[rules_dir.join("prepositions.txt")],
            SimpleReplaceConfig {
                rule_id: "NDM_PREPOSITIONS",
                description: "Nordum preposition spelling ($match)",
                short: "Preposition",
                message: "In Nordum the preposition is written '$suggestions', not '$match'.",
                suggestions_separator: " or ",
                sub_rule_specific_ids: false,
                case_sensitivity: CaseSensitivity::Ci,
                category_id: "GRAMMAR",
                category_name: "Grammar",
                issue_type: "grammar",
                default_off: false,
                picky: false,
                has_suggestions: true,
                checking_case: false,
                ignore_short_uppercase_words: true,
                is_token_exception: crate::simple_replace::TokenException::None,
            },
        )?,
        SimpleReplaceRule::from_files(
            &[rules_dir.join("loanwords.txt")],
            SimpleReplaceConfig {
                rule_id: "NDM_LOANWORDS",
                description: "Loanword preference ($match)",
                short: "Loanword",
                message: "Nordum keeps this loanword in its international form: $suggestions.",
                suggestions_separator: " or ",
                sub_rule_specific_ids: false,
                case_sensitivity: CaseSensitivity::Ci,
                category_id: "STYLE",
                category_name: "Style",
                issue_type: "style",
                default_off: false,
                picky: false,
                has_suggestions: true,
                checking_case: false,
                ignore_short_uppercase_words: true,
                is_token_exception: crate::simple_replace::TokenException::None,
            },
        )?,
        // `AbstractCheckCaseRule`: the file lists the *correct* forms; any
        // other casing is flagged (sentence start is exempted).
        SimpleReplaceRule::from_files(
            &[rules_dir.join("check_case.txt")],
            SimpleReplaceConfig {
                rule_id: "NDM_CAPITALIZATION",
                description: "Nordum capitalization ($match)",
                short: "Capitalization",
                message: "Nordum uses sentence case: write '$suggestions', not '$match'.",
                suggestions_separator: ", ",
                sub_rule_specific_ids: false,
                case_sensitivity: CaseSensitivity::Ci,
                category_id: "CASING",
                category_name: "Capitalization",
                issue_type: "typographical",
                default_off: false,
                picky: false,
                has_suggestions: true,
                checking_case: true,
                ignore_short_uppercase_words: false,
                is_token_exception: crate::simple_replace::TokenException::None,
            },
        )?,
        SimpleReplaceRule::from_files(
            &[rules_dir.join("endonyms.txt")],
            SimpleReplaceConfig {
                rule_id: "NDM_ENDONYMS",
                description: "Endonym preference ($match)",
                short: "Endonym",
                message: "Nordum prefers the endonym: $suggestions.",
                suggestions_separator: " or ",
                sub_rule_specific_ids: false,
                case_sensitivity: CaseSensitivity::Ci,
                category_id: "STYLE",
                category_name: "Style",
                issue_type: "style",
                default_off: false,
                picky: false,
                has_suggestions: true,
                checking_case: false,
                ignore_short_uppercase_words: true,
                is_token_exception: crate::simple_replace::TokenException::None,
            },
        )?,
    ])
}
