// Generated by tools/gen-es-priorities.py from the pinned Spanish.java
// id2prio map — do not edit by hand. The key order is sorted for
// binary search; Java's map lookup is order-independent.

// entry count: 55
pub(crate) static ES_PRIORITIES: &[(&str, i32)] = &[
    ("AGREEMENT_ADJ_NOUN", -30),
    ("AGREEMENT_ADJ_NOUN_AREA", 30),
    ("AGREEMENT_DET_ABREV", 25),
    ("AGREEMENT_DET_ADJ", 10),
    ("AGREEMENT_DET_NOUN", 15),
    ("AGREEMENT_DET_NOUN_EXCEPTIONS", 25),
    ("AGREEMENT_PARTICIPLE_NOUN", -30),
    ("AGREEMENT_POSTPONED_ADJ", -30),
    ("COMMA_SINO", -40),
    ("COMMA_SINO2", -40),
    ("CONFUSION_ES_SE", 20),
    ("DEGREE_CHAR", 30),
    ("DE_TILDE", 50),
    ("EL_NO_TILDE", 40),
    ("EL_TILDE", -10),
    ("ES_QUESTION_MARK", -250),
    ("ES_SIMPLE_REPLACE_MULTIWORDS", 50),
    ("ES_SPLIT_WORDS", -10),
    ("ETCETERA", 30),
    ("HALLA_HAYA", 10),
    ("LOS_MAPUCHE", 50),
    ("LO_LOS", 30),
    ("MORFOLOGIK_RULE_ES", -100),
    ("MUCHO_NF", 25),
    ("MULTI_ADJ", -30),
    ("NO_SEPARADO", 40),
    ("PARTICIPIO_MS", 40),
    ("PERSONAJES_FAMOSOS", 50),
    ("PHRASE_REPETITION", -150),
    ("PLURAL_SEPARADO", 50),
    ("POR_CIERTO", 30),
    ("PREP_VERB", -20),
    ("PRIMER_PRIMERA", 20),
    ("PRONOMBRE_SIN_VERBO", 25),
    ("P_EJ", 30),
    ("REPETITIONS_STYLE", -50),
    ("SEPARADO", 1),
    ("SE_CREO", 35),
    ("SE_CREO2", 25),
    ("SINGLE_CHARACTER", -15),
    ("SI_AFIRMACION", 10),
    ("SPANISH_WORD_REPEAT_RULE", -150),
    ("SUBJUNTIVO_FUTURO", -30),
    ("SUBJUNTIVO_INCORRECTO", -40),
    ("SUBJUNTIVO_PASADO", -30),
    ("SUBJUNTIVO_PASADO2", -30),
    ("TE_TILDE", 50),
    ("TE_TILDE2", 10),
    ("TOO_LONG_PARAGRAPH", -15),
    ("TYPOGRAPHY", 20),
    ("UPPERCASE_SENTENCE_START", -200),
    ("U_NO", -10),
    ("VALLA_VAYA", 10),
    ("VERBO_MODAL_INFINITIVO", 40),
    ("VOSEO", -40),
];

/// `Spanish.getPriorityForId`: explicit map, then the id-prefix fallbacks,
/// then the base `Language.getPriorityForId` fallbacks.
pub fn priority_for_id(id: &str) -> i32 {
    if id == "CONFUSIONS2" {
        return 50; // greater than CONFUSIONS
    }
    if id == "RARE_WORDS" {
        return 50;
    }
    if id == "MISSPELLING" {
        return 40;
    }
    if id == "CONFUSIONS" {
        return 40;
    }
    if id == "INCORRECT_EXPRESSIONS" {
        return 40;
    }
    if id == "DIACRITICS" {
        return 30;
    }
    if id.starts_with("ES_SIMPLE_REPLACE_SIMPLE") {
        return 30;
    }
    if id.starts_with("ES_COMPOUNDS") {
        return 50;
    }
    if let Ok(index) = ES_PRIORITIES.binary_search_by(|(key, _)| (*key).cmp(id)) {
        return ES_PRIORITIES[index].1;
    }
    if id.starts_with("AI_ES_HYDRA_LEO") {
        // prefer more specific rules (also speller)
        return -101;
    }
    if id.starts_with("AI_ES_GGEC") {
        // prefer more specific rules (also speller)
        if id == "AI_ES_GGEC_REPLACEMENT_OTHER" {
            return -300;
        }
        return 0;
    }
    if id.starts_with("ES_MULTITOKEN_SPELLING") {
        return -95;
    }
    // base `Language.getPriorityForId`
    if id.eq_ignore_ascii_case("TOO_LONG_SENTENCE") {
        return -101;
    }
    if id == "REPETITIONS_STYLE" {
        return -55;
    }
    if id.contains("STYLE") {
        return -50;
    }
    0
}

/// `Language.getRulePriority` for Spanish. Spanish does not override
/// `getDefaultRulePriorityForStyle`, so the issue-type fallback is 0 (unlike
/// English).
pub fn rule_priority(
    rule_id: &str,
    category_id: &str,
    issue_type: &str,
    rule_priority: i32,
) -> i32 {
    let _ = issue_type;
    let rule_specific = priority_for_id(rule_id);
    if rule_specific != 0 {
        return rule_specific;
    }
    if rule_priority != 0 {
        return rule_priority;
    }
    let category = priority_for_id(category_id);
    if category != 0 {
        return category;
    }
    0
}
