// Generated by tools/gen-fr-priorities.py from the pinned French.java
// id2prio map — do not edit by hand. The key order is sorted for
// binary search; Java's map lookup is order-independent.

// entry count: 99
pub(crate) static FR_PRIORITIES: &[(&str, i32)] = &[
    ("ACCORD_CHAQUE", 100),
    ("ACCORD_PLURIEL_ORDINAUX", 10),
    ("ACCORD_R_PERS_VERBE", 10),
    ("ADJ_ADJ_SENT_END", 10),
    ("AGREEMENT_EXCEPTIONS", 100),
    ("AGREEMENT_POSTPONED_ADJ", -50),
    ("AGREEMENT_TOUT_LE", 10),
    ("AN_EN", 10),
    ("APOS_M", 10),
    ("A_ACCENT", 10),
    ("A_ACCENT_A", 10),
    ("A_A_ACCENT", 10),
    ("A_A_ACCENT2", 10),
    ("A_INFINITIF", 100),
    ("A_LE", -50),
    ("A_VERBE_INFINITIF", 20),
    ("BYTES", 10),
    ("CEST_A_DIRE", 100),
    ("CONFUSION_AL_LA", -50),
    ("CONFUSION_PARLEZ_PARLER", 10),
    ("COTE", 10),
    ("DE_OU_DES", 20),
    ("DU_DU", 100),
    ("D_N_E_OU_E", 100),
    ("D_VPPA", 20),
    ("ELISION", -200),
    ("EMPLOI_EMPLOIE", 20),
    ("EN_CE_QUI_CONCERNE", -152),
    ("EN_MEME_TEMPS", -152),
    ("ESPACE_UNITES", 10),
    ("EST_CE_QUE", 20),
    ("ET_AUSSI", -152),
    ("ET_SENT_START", -151),
    ("EXPRESSIONS_VU", 100),
    ("FAIRE_VPPA", 100),
    ("FRENCH_WHITESPACE", -400),
    ("FRENCH_WHITESPACE_STRICT", -350),
    ("FRENCH_WORD_REPEAT_BEGINNING_RULE", -350),
    ("FRENCH_WORD_REPEAT_RULE", -20),
    ("FR_SPELLING_RULE", -100),
    ("FR_SPLIT_WORDS_HYPHEN", 100),
    ("GENS_ACCORD", 100),
    ("ILS_VERBE", -50),
    ("IL_VERBE", -50),
    ("IMP_PRON", -10),
    ("INTERROGATIVE_DIRECTE", -10),
    ("JE_M_APPEL", 10),
    ("JE_SUI", 10),
    ("JE_TES", 100),
    ("J_N", -10),
    ("J_N2", 100),
    ("LA_LA2", -20),
    ("LEURS_LEUR", 100),
    ("LE_COVID", -60),
    ("MA", 100),
    ("MAIS_AUSSI", -152),
    ("MAIS_SENT_START", -151),
    ("MOTS_INCOMP", -400),
    ("MOT_TRAIT_MOT", -400),
    ("MULTI_ADJ", -50),
    ("ON_ONT", 100),
    ("OU_PAS", 10),
    ("PARENTHESES", -50),
    ("PAS_DE_SOUCIS", 10),
    ("PAS_DE_TRAIT_UNION", 50),
    ("PAS_DE_VERBE_APRES_POSSESSIF_DEMONSTRATIF", -20),
    ("PEUTETRE", 10),
    ("PLACE_DE_LA_VIRGULE", 10),
    ("PLURIEL_AL2", 100),
    ("POINT", -200),
    ("POINTS_2", -400),
    ("POINTS_SUSPENSIONS_SPACE", -250),
    ("PREP_VERBECONJUGUE", -20),
    ("QUASI_NOM", 100),
    ("REPETITIONS_STYLE", -250),
    ("REP_ESSENTIEL", -50),
    ("R_VAVOIR_VINF", 10),
    ("SA_CA_SE", 100),
    ("SE_CE", -10),
    ("SIL_VOUS_PLAIT", 100),
    ("SOCIOCULTUREL", 40),
    ("SON_SONT", 100),
    ("SUJET_AUXILIAIRE", 10),
    ("TE_NV", -20),
    ("TE_NV2", -10),
    ("TOO_LONG_PARAGRAPH", -15),
    ("TOUT_MAJUSCULES", -400),
    ("TRAIT_UNION", 100),
    ("TRES_TRES_ADJ", -10),
    ("UPPERCASE_SENTENCE_START", -300),
    ("VERBES_FAMILIERS", -25),
    ("VERB_PRONOUN", -50),
    ("VIRGULE_EXPRESSIONS_FIGEES", 100),
    ("VIRGULE_VERBE", -20),
    ("VIRG_INF", -100),
    ("VIRG_NON_TROUVEE", -400),
    ("VOIR_VOIRE", 20),
    ("V_J_A_R", -10),
    ("Y_A", 10),
];

/// `French.getPriorityForId`: explicit map, then the id-prefix fallbacks,
/// then the base `Language.getPriorityForId` fallbacks.
pub fn priority_for_id(id: &str) -> i32 {
    if id.starts_with("FR_COMPOUNDS") {
        return 500;
    }
    if id == "CAT_TYPOGRAPHIE" {
        return 20; // greater than PRONSUJ_NONVERBE or agreement rules
    }
    if id == "CAT_TOURS_CRITIQUES" {
        return 20;
    }
    if id == "CAT_HOMONYMES_PARONYMES" {
        return 20;
    }
    if id == "SON" {
        return -5; // less than ETRE_VPPA_OU_ADJ
    }
    if id.starts_with("CAR") {
        return -50; // lesser than grammar rules
    }
    if id == "CONFUSION_RULE_PREMIUM" {
        return -50; // lesser than PRONSUJ_NONVERBE
    }
    if id.starts_with("FR_MULTITOKEN_SPELLING_") {
        return -90;
    }
    if id.starts_with("FR_SIMPLE_REPLACE") {
        return 150;
    }
    if id.starts_with("grammalecte_") {
        return -150;
    }
    if id.starts_with("AI_FR_HYDRA_LEO") {
        // prefer more specific rules (also speller)
        return -101;
    }
    if id.starts_with("AI_FR_GGEC_REPLACEMENT_ORTHOGRAPHY") {
        // prefer more specific rules (also speller)
        return -101;
    }
    if let Ok(index) = FR_PRIORITIES.binary_search_by(|(key, _)| (*key).cmp(id)) {
        return FR_PRIORITIES[index].1;
    }
    // base `Language.getPriorityForId`
    if id.eq_ignore_ascii_case("TOO_LONG_SENTENCE") {
        return -101;
    }
    if id == "REPETITIONS_STYLE" {
        return -55;
    }
    if id.contains("STYLE") {
        return -50;
    }
    0
}

/// `Language.getRulePriority` for Spanish. French does not override
/// `getDefaultRulePriorityForStyle`, so the issue-type fallback is 0 (unlike
/// English).
pub fn rule_priority(
    rule_id: &str,
    category_id: &str,
    issue_type: &str,
    rule_priority: i32,
) -> i32 {
    let _ = issue_type;
    let rule_specific = priority_for_id(rule_id);
    if rule_specific != 0 {
        return rule_specific;
    }
    if rule_priority != 0 {
        return rule_priority;
    }
    let category = priority_for_id(category_id);
    if category != 0 {
        return category;
    }
    0
}
