//! Language detection.
//!
//! A free function, not an [`LtEngine`](crate::LtEngine) method: deciding the
//! language is precisely what picks the engine, so a caller has to be able to
//! ask before any engine exists.
//!
//! The layers, the gates and the ranking are `lt_core::detect`'s and the
//! statistical model is `lt::detect_model`'s — both are embedded in the wasm
//! binary (the model with `include_bytes!`, the Nordum markers below), so a
//! browser fetches no detection asset. This module only decides what a JSON
//! caller gets to see: the settled answer plus the ranking behind it, and
//! nothing more.

use std::sync::OnceLock;

use lt_core::detect::{self, Gates, Lexicon, Source};
use lt_core::Lang;
use serde::Deserialize;
use wasm_bindgen::prelude::*;

use crate::js_error;

/// The Nordum-only words, embedded the way the model is: generated by
/// `tools/detection/generate.py`, committed at `data/nrd/detection/markers.txt`
/// and read at compile time, so the browser build needs no fetch. Nordum has
/// no statistical model and is decided here and nowhere else.
const NORDUM_MARKERS: &str = include_str!("../../../data/nrd/detection/markers.txt");

/// The marker lexicon, built once per process.
///
/// Nordum is the only language with markers today; a caller that adds another
/// language adds a `load` here and nothing else.
fn lexicon() -> &'static Lexicon {
    static LEXICON: OnceLock<Lexicon> = OnceLock::new();
    LEXICON.get_or_init(|| {
        let mut lexicon = Lexicon::new();
        lexicon.load(Lang::Nrd, NORDUM_MARKERS);
        lexicon
    })
}

/// Gate overrides accepted as JSON by [`detect_json`]; all fields optional.
///
/// Fields default per field to the [`Gates::default()`] value they shadow, so
/// `{}` is the same call as no argument at all.
#[derive(Debug, Deserialize)]
#[serde(default, rename_all = "camelCase")]
struct WasmGates {
    min_chars: usize,
    min_confidence: f32,
    min_margin: f32,
    non_latin_weight: usize,
}

impl Default for WasmGates {
    fn default() -> Self {
        let gates = Gates::default();
        WasmGates {
            min_chars: gates.min_chars,
            min_confidence: gates.min_confidence,
            min_margin: gates.min_margin,
            non_latin_weight: gates.non_latin_weight,
        }
    }
}

impl From<WasmGates> for Gates {
    fn from(gates: WasmGates) -> Gates {
        Gates {
            min_chars: gates.min_chars,
            min_confidence: gates.min_confidence,
            min_margin: gates.min_margin,
            non_latin_weight: gates.non_latin_weight,
        }
    }
}

/// One scored language: `{"language":"sv","confidence":0.93,"source":"model"}`.
#[derive(serde::Serialize)]
struct Scored {
    language: &'static str,
    confidence: f32,
    source: &'static str,
}

impl Scored {
    fn new(lang: Lang, confidence: f32, source: Source) -> Scored {
        Scored {
            language: lang.base_code(),
            confidence,
            // The same strings `/v3/detect` reports, from the same definition, so
            // an HTTP response and a wasm result cannot spell the same layer two
            // ways.
            source: detect::source_name(source),
        }
    }
}

/// JSON body of [`detect_json`].
#[derive(serde::Serialize)]
struct DetectionReport {
    /// The language to use, or `null` when detection abstained.
    resolved: Option<&'static str>,
    /// The settled answer, or `null` alongside `resolved`.
    detected: Option<Scored>,
    /// Everything considered, best first — present even when the gates
    /// abstain, so a UI can offer the ranking as a suggestion without treating
    /// it as a decision. Empty only when neither layer produced anything.
    candidates: Vec<Scored>,
}

/// Detect the language of `text` and return the decision as JSON:
/// `{"resolved":"sv","detected":{…},"candidates":[…]}`.
///
/// `gates` is an optional JSON object overriding the thresholds
/// (`{"minChars":20,"minConfidence":0.6,"minMargin":1.5}`); absent means
/// [`Gates::default()`].
///
/// `resolved` is `null` when the gates abstain — the text is too short, too
/// ambiguous, or carries no marker. That is a normal outcome, not an error: the
/// caller keeps whatever language it was already using.
///
/// ```js
/// import init, { detect_json } from "./pkg/lt_wasm.js";
/// await init();
/// JSON.parse(detect_json("Jag kommer hem efter jobbet.")).resolved; // "sv"
/// ```
#[wasm_bindgen]
pub fn detect_json(text: &str, gates: Option<String>) -> Result<String, JsError> {
    let gates = match &gates {
        Some(json) => Gates::from(serde_json::from_str::<WasmGates>(json).map_err(js_error)?),
        None => Gates::default(),
    };
    let lexicon = lexicon();
    let model = lt::detect_model::bundled();
    let refiner = lt::detect_refiner::bundled();
    // Two passes over the model, one per `lt_core::detect` entry point, so the
    // ranking and the decision come from the same implementation of the gates
    // rather than from a second copy of the gate logic here. A prediction costs
    // tens of microseconds, which is not worth a memoizing wrapper.
    let candidates = detect::candidates(text, lexicon, model, refiner, &gates);
    let detected = detect::detect(text, lexicon, model, refiner, &gates);
    let report = DetectionReport {
        resolved: detected.map(|hit| hit.language.base_code()),
        detected: detected.map(|hit| Scored::new(hit.language, hit.confidence, hit.source)),
        candidates: candidates
            .into_iter()
            .map(|candidate| Scored::new(candidate.lang, candidate.confidence, candidate.source))
            .collect(),
    };
    serde_json::to_string(&report).map_err(js_error)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_markers_are_loaded() {
        assert_eq!(lexicon().languages(), vec![Lang::Nrd]);
        assert_eq!(
            lexicon()
                .identify("Jei vet at hun arbeider i dag.")
                .map(|(lang, _)| lang),
            Some(Lang::Nrd)
        );
    }

    #[test]
    fn gate_overrides_default_per_field() {
        let default: Gates = WasmGates::default().into();
        assert_eq!(default, Gates::default());

        let empty: Gates = serde_json::from_str::<WasmGates>("{}")
            .expect("parses")
            .into();
        assert_eq!(empty, Gates::default());

        let partial: Gates = serde_json::from_str::<WasmGates>(r#"{"minChars": 5}"#)
            .expect("parses")
            .into();
        assert_eq!(partial.min_chars, 5);
        assert_eq!(partial.min_confidence, Gates::default().min_confidence);
        assert_eq!(partial.min_margin, Gates::default().min_margin);
    }

    /// Asserted here rather than through `detect_json`: `JsError::new` calls a
    /// wasm import and panics on the host, so the error path itself cannot be
    /// taken from a host test.
    #[test]
    fn malformed_gate_json_is_rejected() {
        assert!(serde_json::from_str::<WasmGates>("nope").is_err());
        assert!(serde_json::from_str::<WasmGates>(r#"{"minChars": -1}"#).is_err());
        assert!(serde_json::from_str::<WasmGates>(r#"{"minConfidence": "high"}"#).is_err());
        assert!(serde_json::from_str::<WasmGates>(r#"{"minMargin": {}}"#).is_err());
    }

    #[test]
    fn sources_are_named_for_the_json() {
        // The serialised `source` strings, pinned. `fasttext` rather than
        // `model` because `/v3/detect` reports the implementation and both
        // surfaces share `lt_core::detect::source_name`; a wasm client and an
        // HTTP client must see the same word for the same layer.
        let json = serde_json::to_string(&Scored::new(Lang::Nrd, 0.95, Source::Lexicon)).unwrap();
        assert_eq!(
            json,
            r#"{"language":"nrd","confidence":0.95,"source":"lexicon"}"#
        );
        let json = serde_json::to_string(&Scored::new(Lang::Sv, 0.93, Source::Model)).unwrap();
        assert_eq!(
            json,
            r#"{"language":"sv","confidence":0.93,"source":"fasttext"}"#
        );
        let json =
            serde_json::to_string(&Scored::new(Lang::No, 0.99, Source::Discriminator)).unwrap();
        assert_eq!(
            json,
            r#"{"language":"no","confidence":0.99,"source":"discriminator"}"#
        );
    }
}
