//! Binary container for vendored data packs.
//!
//! A pack is a single file that bundles the `data/` files an engine needs at
//! runtime, so a wasm build (which has no file system) can serve them from
//! memory. The format is deliberately trivial to parse in Rust and to produce
//! from a build script:
//!
//! ```text
//! magic   b"LTPK1"                      (5 bytes)
//! count   u32 LE
//! entries count × { path_len: u16 LE, path: UTF-8 bytes,
//!                   offset: u64 LE, len: u64 LE }
//! payload bytes (offsets are absolute from the start of the pack)
//! ```
//!
//! Paths are `/`-separated and relative to the data directory
//! (`core/segment.srx`, `en/rules/grammar.xml`, …).
//!
//! Packs are generated by `pack_data` (see `src/bin/pack_data.rs`) and
//! registered as an in-memory mount by `DataDir::from_pack`.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use lt_core::{CoreError, Result};

const MAGIC: &[u8; 5] = b"LTPK1";
const HEADER_BASE: usize = MAGIC.len() + 4;
const ENTRY_LEN: usize = 2 + 8 + 8;

fn data_error(message: impl Into<String>) -> CoreError {
    CoreError::Data(message.into())
}

/// Parse a pack into an index of `relative path -> (offset, len)`.
pub fn parse(bytes: &[u8]) -> Result<HashMap<PathBuf, (usize, usize)>> {
    if bytes.len() < HEADER_BASE || &bytes[..MAGIC.len()] != MAGIC {
        return Err(data_error("not a LingoTweaker data pack (bad magic)"));
    }
    let count = u32::from_le_bytes(
        bytes[MAGIC.len()..HEADER_BASE]
            .try_into()
            .map_err(|_| data_error("truncated pack header"))?,
    ) as usize;
    let header_end = HEADER_BASE
        .checked_add(
            count
                .checked_mul(ENTRY_LEN)
                .ok_or_else(|| data_error("pack entry count overflows"))?,
        )
        .ok_or_else(|| data_error("pack header size overflows"))?;
    if bytes.len() < header_end {
        return Err(data_error("truncated pack entry table"));
    }

    let mut index = HashMap::with_capacity(count);
    let mut cursor = HEADER_BASE;
    for _ in 0..count {
        let path_len = u16::from_le_bytes(bytes[cursor..cursor + 2].try_into().unwrap()) as usize;
        cursor += 2;
        let path_end = cursor + path_len;
        if path_end + 16 > bytes.len() {
            return Err(data_error("truncated pack entry"));
        }
        let path = std::str::from_utf8(&bytes[cursor..path_end])
            .map_err(|e| data_error(format!("pack path is not UTF-8: {e}")))?;
        if path.is_empty() || path.starts_with('/') || path.contains('\\') {
            return Err(data_error(format!("invalid pack path: {path:?}")));
        }
        cursor = path_end;
        let offset = u64::from_le_bytes(bytes[cursor..cursor + 8].try_into().unwrap()) as usize;
        cursor += 8;
        let len = u64::from_le_bytes(bytes[cursor..cursor + 8].try_into().unwrap()) as usize;
        cursor += 8;
        let end = offset
            .checked_add(len)
            .ok_or_else(|| data_error(format!("pack entry {path:?} overflows")))?;
        if end > bytes.len() {
            return Err(data_error(format!("pack entry {path:?} is out of bounds")));
        }
        if index.insert(PathBuf::from(path), (offset, len)).is_some() {
            return Err(data_error(format!("duplicate pack path: {path:?}")));
        }
    }
    Ok(index)
}

/// Serialize `(relative path, bytes)` pairs into a pack.
///
/// Entries are sorted by path for reproducible output.
pub fn write(files: &[(PathBuf, Vec<u8>)]) -> Vec<u8> {
    let mut entries: Vec<&(PathBuf, Vec<u8>)> = files.iter().collect();
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let paths: Vec<&[u8]> = entries
        .iter()
        .map(|(path, _)| path.to_str().expect("pack paths are UTF-8").as_bytes())
        .collect();
    let header_len: usize =
        HEADER_BASE + entries.len() * ENTRY_LEN + paths.iter().map(|p| p.len()).sum::<usize>();

    let mut header = Vec::with_capacity(header_len);
    header.extend_from_slice(MAGIC);
    header.extend_from_slice(&(entries.len() as u32).to_le_bytes());
    let mut offset = header_len;
    for (path_bytes, (_, bytes)) in paths.iter().zip(&entries) {
        header.extend_from_slice(&(path_bytes.len() as u16).to_le_bytes());
        header.extend_from_slice(path_bytes);
        header.extend_from_slice(&(offset as u64).to_le_bytes());
        header.extend_from_slice(&(bytes.len() as u64).to_le_bytes());
        offset += bytes.len();
    }
    debug_assert_eq!(header.len(), header_len);

    let mut out = header;
    out.reserve(offset - out.len());
    for (_, bytes) in &entries {
        out.extend_from_slice(bytes);
    }
    out
}

/// Files that belong to a language pack: `core/**` and everything under
/// `data/<lang>/`.
///
/// This is deliberately conservative (it also ships variant files and lists
/// the default variant does not open) so a pack can never miss a runtime
/// dependency; the extra bytes are small compared with the dictionaries.
///
/// `manifest.json` (a per-file provenance record for the vendored data) and
/// `messages/**` (upstream UI translations) are intentionally excluded: the
/// engine never reads them at runtime, and for small languages they doubled
/// the pack size.
pub fn collect_language(data_dir: &Path, lang: &str) -> Result<Vec<(PathBuf, Vec<u8>)>> {
    let mut files = Vec::new();
    collect_tree(data_dir, &data_dir.join("core"), &mut files)?;
    collect_tree(data_dir, &data_dir.join(lang), &mut files)?;
    if files.is_empty() {
        return Err(data_error(format!(
            "no data found for language {lang:?} under {}",
            data_dir.display()
        )));
    }
    Ok(files)
}

fn collect_tree(data_dir: &Path, dir: &Path, files: &mut Vec<(PathBuf, Vec<u8>)>) -> Result<()> {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(data_error(format!("cannot read {}: {e}", dir.display()))),
    };
    let mut paths: Vec<PathBuf> = entries.filter_map(|e| e.ok().map(|e| e.path())).collect();
    paths.sort();
    for path in paths {
        if path.is_dir() {
            collect_tree(data_dir, &path, files)?;
        } else {
            push_file(data_dir, &path, files)?;
        }
    }
    Ok(())
}

fn push_file(data_dir: &Path, path: &Path, files: &mut Vec<(PathBuf, Vec<u8>)>) -> Result<()> {
    let rel = path
        .strip_prefix(data_dir)
        .map_err(|_| {
            data_error(format!(
                "{} is outside {}",
                path.display(),
                data_dir.display()
            ))
        })?
        .to_path_buf();
    let bytes = std::fs::read(path)
        .map_err(|e| data_error(format!("cannot read {}: {e}", path.display())))?;
    files.push((rel, bytes));
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips() {
        let files = vec![
            (PathBuf::from("core/a.txt"), b"hello".to_vec()),
            (PathBuf::from("en/rules/grammar.xml"), b"<rules/>".to_vec()),
        ];
        let pack = write(&files);
        let index = parse(&pack).expect("pack parses");
        assert_eq!(index.len(), 2);
        let (offset, len) = index[Path::new("en/rules/grammar.xml")];
        assert_eq!(&pack[offset..offset + len], b"<rules/>");
        let (offset, len) = index[Path::new("core/a.txt")];
        assert_eq!(&pack[offset..offset + len], b"hello");
    }

    #[test]
    fn rejects_bad_magic_and_truncation() {
        assert!(parse(b"nope").is_err());
        let pack = write(&[(PathBuf::from("a"), b"x".to_vec())]);
        assert!(parse(&pack[..pack.len() - 1]).is_err());
        assert!(parse(&pack[..8]).is_err());
    }
}
