//! Language detection for the HTTP layer.
//!
//! The layers, the gates and the ranking all belong to [`lt_core::detect`]; this
//! module only supplies them with the two inputs they need — the bundled
//! statistical model (`lt::detect_model`, reached through the `lt` facade so
//! `lt-http` never depends on `fasttext-pure-rs` itself) and the Nordum marker
//! list — and turns the result into the two shapes the API needs.
//!
//! Both inputs are lazy. The model costs ~8 ms to parse plus ~900 kB, and the
//! marker list a few kB, so a process that only ever checks with an explicit
//! `language=` never pays either: `language=<explicit>` does not call into this
//! module at all.
//!
//! ## What `source` reports
//!
//! LT's open-source server labels its detector `"ngram"`
//! (`DefaultLanguageIdentifier.java:258`, reached from `TextChecker.java:1033`),
//! and the field is a free-form diagnostic: LT itself composes it
//! (`"ngram+commonwords"`, `"ngram+fallback"`, `"ngram+prefLang(forced: false)"`)
//! and no client branches on it — `RemoteLanguageTool` reads only `code` and
//! `name` out of `detectedLanguage`.
//!
//! v2 therefore reports [`V2_MODEL_SOURCE`] for a statistical decision, which is
//! both what an LT server sends and true of fastText, which classifies hashed
//! character n-grams with a linear layer. A Nordum hit is decided by a word
//! list rather than by n-gram statistics, so it reports [`V2_LEXICON_SOURCE`]
//! instead of borrowing the n-gram name. `/v3/detect` ([`MODEL_SOURCE`]) has no
//! compatibility duty and names the implementation outright.

use std::sync::OnceLock;

use lt_core::detect::{self, Candidate, Detection, Gates, Lexicon, Source};
use lt_core::Lang;
use serde_json::{json, Value};

/// The Nordum-only words, embedded the way the model is: generated by
/// `tools/detection/generate.py`, committed at `data/nrd/detection/markers.txt`
/// and read at compile time. Nordum is the one language with no statistical
/// model — `lid.176.ftz` has no `nrd` label and answers `da`/`no`/`sv` for it
/// with up to 0.99 confidence — so it is decided here and nowhere else.
const NORDUM_MARKERS: &str = include_str!("../../../data/nrd/detection/markers.txt");

/// `source` for a statistical decision on the v2 surface. See the module docs:
/// this is the literal `DefaultLanguageIdentifier` emits, and fastText is an
/// n-gram method.
pub const V2_MODEL_SOURCE: &str = "ngram";

/// `source` for an exclusive-word decision on the v2 surface.
pub const V2_LEXICON_SOURCE: &str = "lexicon";

/// `source` for a statistical decision on `/v3/detect`. No LT client to keep
/// happy here, so it says what actually ran. Shared with the wasm binding
/// through `lt_core::detect`, so the two surfaces cannot drift apart.
pub use lt_core::detect::{
    SOURCE_DISCRIMINATOR as DISCRIMINATOR_SOURCE, SOURCE_LEXICON as LEXICON_SOURCE,
    SOURCE_MODEL as MODEL_SOURCE,
};

/// The marker lexicon, built once per process.
fn lexicon() -> &'static Lexicon {
    static LEXICON: OnceLock<Lexicon> = OnceLock::new();
    LEXICON.get_or_init(|| {
        let mut lexicon = Lexicon::new();
        lexicon.load(Lang::Nrd, NORDUM_MARKERS);
        lexicon
    })
}

/// Detection of one text: the decision if the gates cleared, and the ranking
/// either way.
pub struct Outcome {
    /// The settled answer, or `None` when the gates abstained — too short, too
    /// ambiguous, or no evidence at all. An abstention is a normal outcome: the
    /// caller keeps the language it already had.
    pub detected: Option<Detection>,
    /// Everything considered, best first.
    pub candidates: Vec<Candidate>,
}

impl Outcome {
    /// The leading candidate, or `None` if there was none.
    pub fn best(&self) -> Option<&Candidate> {
        self.candidates.first()
    }
}

/// Decide the language of `text`, restricted to `restrict` when it is `Some`.
///
/// `restrict` is the set of languages the caller has data for: on `/v3/detect`
/// it lets a client narrow detection to the packs it ships. `None` means no
/// restriction; `Some(&[])` therefore narrows to nothing and answers `null`,
/// which is the honest result for a client that named only languages this build
/// does not ship. The lexicon layer is filtered by it too — a caller that asked
/// for `sv,en` does not want `nrd` just because the text contains a Nordum
/// marker.
///
/// One model pass feeds both the ranking and the decision, rather than calling
/// `lt_core::detect::candidates` and `lt_core::detect::detect` in turn the way
/// the wasm binding does: here the ranking is frequently reported alongside the
/// decision (and per sentence), so a second prediction per request would show
/// up in the response time. The gate rules are `lt_core::detect`'s, applied by
/// `lt_core::detect::cleared_candidates`, so the two surfaces cannot drift.
/// `gates` is `None` for the calibrated defaults. Detection is cheap enough that
/// this is not worth an `Option` at every call site, but a caller that has tuned
/// the gates passes them and gets exactly the behaviour it asked for.
pub fn language_of(text: &str, restrict: Option<&[Lang]>, gates: Option<&Gates>) -> Outcome {
    let gates = gates.copied().unwrap_or_default();
    let lexicon = lexicon();
    let model = lt::detect_model::bundled();
    let refiner = lt::detect_refiner::bundled();
    let candidates = detect::candidates(text, lexicon, model, refiner, &gates);
    let candidates: Vec<Candidate> = candidates
        .into_iter()
        .filter(|candidate| restrict.is_none_or(|restrict| restrict.contains(&candidate.lang)))
        .collect();
    let detected = detect::cleared_candidates(&candidates, text, &gates);
    Outcome {
        detected,
        candidates,
    }
}

/// `source` string for the v2 response.
///
/// Both statistical layers report `"ngram"`: that is the vocabulary
/// LanguageTool's own API uses for this (`TextChecker.java:993-1033`), and both
/// of ours are n-gram models. The v2 surface is a drop-in, so it does not grow a
/// value its clients have never seen.
pub fn v2_source(source: Source) -> &'static str {
    match source {
        Source::Lexicon => V2_LEXICON_SOURCE,
        Source::Model | Source::Discriminator => V2_MODEL_SOURCE,
    }
}

/// `source` string for the `/v3/detect` response.
pub fn v3_source(source: Source) -> &'static str {
    detect::source_name(source)
}

/// `{"language":"sv","confidence":0.93,"source":"fasttext"}` — the wasm
/// binding's `Scored`, field for field.
pub fn scored_json(candidate: &Candidate) -> Value {
    json!({
        "language": candidate.lang.base_code(),
        "confidence": candidate.confidence,
        "source": v3_source(candidate.source),
    })
}

/// Body of `POST /v3/detect`.
///
/// `detected` is `null` whenever `resolved` is, so a client can read one field
/// or the other; `candidates` is populated either way, because a ranking is a
/// usable suggestion where a decision is not.
pub fn report_json(outcome: &Outcome) -> Value {
    let detected = outcome.detected;
    json!({
        "detected": detected.map(|hit| json!({
            "language": hit.language.base_code(),
            "confidence": hit.confidence,
            "source": v3_source(hit.source),
        })),
        "candidates": outcome.candidates.iter().map(scored_json).collect::<Vec<Value>>(),
        "resolved": detected.map(|hit| hit.language.base_code()),
    })
}

/// Parse a `restrict=` list into languages, dropping codes this build does not
/// know.
///
/// Unknown entries are ignored rather than rejected: the parameter exists so a
/// client can name the packs it has, and a client naming one we do not ship
/// should still get an answer for the ones we do.
pub fn parse_restrict(value: Option<&str>) -> Vec<Lang> {
    let Some(value) = value else {
        return Vec::new();
    };
    value
        .split(',')
        .map(str::trim)
        .filter(|code| !code.is_empty())
        .filter_map(Lang::from_long_code)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_embedded_markers_are_loaded() {
        assert_eq!(lexicon().languages(), vec![Lang::Nrd]);
        assert_eq!(
            lexicon()
                .identify("Jei vet at hun arbeider i dag.")
                .map(|(lang, _)| lang),
            Some(Lang::Nrd)
        );
    }

    #[test]
    fn restrict_drops_candidates_and_keeps_known_codes() {
        assert_eq!(parse_restrict(None), Vec::<Lang>::new());
        assert_eq!(
            parse_restrict(Some("sv, en ,de")),
            [Lang::Sv, Lang::En, Lang::De]
        );
        // unknown codes are ignored, not rejected
        assert_eq!(parse_restrict(Some("sv,xx,zz-ZZ")), [Lang::Sv]);
        assert_eq!(parse_restrict(Some("")), Vec::<Lang>::new());
    }

    #[test]
    fn restrict_can_exclude_nordum() {
        let text = "Jei vet at det er viktig å lære språket i dag.";
        let outcome = language_of(text, Some(&[Lang::Sv, Lang::En]), None);
        assert_eq!(outcome.detected, None);
        assert!(outcome.candidates.iter().all(|c| c.lang != Lang::Nrd));
    }

    #[test]
    fn restrict_to_nothing_answers_nothing() {
        // A caller naming only languages this build does not ship gets `null`,
        // not an unrestricted answer.
        let outcome = language_of(
            "Jag arbetar inte i dag, men jag kommer hem efter jobbet.",
            Some(&[]),
            None,
        );
        assert_eq!(outcome.detected, None);
        assert!(outcome.candidates.is_empty());
    }

    #[test]
    fn no_restriction_detects_normally() {
        let text = "Jag arbetar inte i dag, men jag kommer hem efter jobbet.";
        let outcome = language_of(text, None, None);
        assert_eq!(outcome.detected.map(|hit| hit.language), Some(Lang::Sv));
    }

    #[test]
    fn a_nordum_only_restrict_still_gets_the_lexicon_answer() {
        let outcome = language_of("Jei.", Some(&[Lang::Nrd]), None);
        assert_eq!(outcome.detected.map(|hit| hit.language), Some(Lang::Nrd));
        assert_eq!(
            outcome.detected.map(|hit| hit.source),
            Some(Source::Lexicon)
        );
    }

    #[test]
    fn v2_and_v3_name_the_model_differently_and_the_lexicon_the_same() {
        assert_eq!(v2_source(Source::Model), "ngram");
        assert_eq!(v2_source(Source::Lexicon), "lexicon");
        assert_eq!(v3_source(Source::Model), "fasttext");
        assert_eq!(v3_source(Source::Lexicon), "lexicon");
    }

    #[test]
    fn abstention_reports_the_ranking_but_no_decision() {
        let outcome = language_of("Hej.", None, None);
        assert_eq!(outcome.detected, None);
        assert!(
            outcome
                .best()
                .is_none_or(|best| best.confidence.is_finite()),
            "a candidate must always carry a finite confidence"
        );
    }

    #[test]
    fn the_report_matches_the_wasm_binding_shape() {
        let outcome = language_of("Jei.", None, None);
        let report = report_json(&outcome);
        assert_eq!(report["resolved"], "nrd");
        assert_eq!(report["detected"]["language"], "nrd");
        assert_eq!(report["detected"]["source"], "lexicon");
        assert_eq!(report["candidates"][0]["language"], "nrd");
        assert_eq!(report["candidates"][0]["source"], "lexicon");
        assert!(report["detected"]["confidence"].is_number());
    }

    #[test]
    fn an_abstention_reports_a_null_decision() {
        let outcome = language_of("Hej.", None, None);
        let report = report_json(&outcome);
        assert_eq!(report["resolved"], Value::Null);
        assert_eq!(report["detected"], Value::Null);
    }
}
