#!/usr/bin/env python3
"""Generate crates/lt/src/es/priorities.rs from the pinned Java source.

Reads `Spanish.java` from the LanguageTool checkout and emits the `id2prio`
map (insertion order, commented-out lines skipped) as a Rust static, so the
`CleanOverlappingFilter` Spanish priorities cannot drift from Java.

Usage:
  tools/gen-es-priorities.py [--upstream <lt-checkout>] [--out <file>]
"""

import argparse
import os
import re
import sys

DEFAULT_UPSTREAM = os.environ.get(
    "LT_CHECKOUT",
    os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "languagetool"))
)
JAVA_REL = (
    "languagetool-language-modules/es/src/main/java/org/languagetool/language/"
    "Spanish.java"
)
DEFAULT_OUT = "crates/lt/src/es/priorities.rs"


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", default=DEFAULT_UPSTREAM)
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    java_path = os.path.join(args.upstream, JAVA_REL)
    with open(java_path, encoding="utf-8") as f:
        text = f.read()

    entries = []
    for m in re.finditer(r'id2prio\.put\("([^"]+)",\s*(-?\d+)\);', text):
        line_start = text.rfind("\n", 0, m.start()) + 1
        prefix = text[line_start : m.start()].strip()
        if prefix.startswith("//"):
            continue
        entries.append((m.group(1), int(m.group(2))))

    entries.sort(key=lambda e: e[0])
    out = [
        "// Generated by tools/gen-es-priorities.py from the pinned Spanish.java",
        "// id2prio map — do not edit by hand. The key order is sorted for",
        "// binary search; Java's map lookup is order-independent.",
        "",
        "// entry count: %d" % len(entries),
        "pub(crate) static ES_PRIORITIES: &[(&str, i32)] = &[",
    ]
    for key, value in entries:
        out.append(f"    ({rust_str(key)}, {value}),")
    out.append("];")
    out.append("")
    out.append(
        """
/// `Spanish.getPriorityForId`: explicit map, then the id-prefix fallbacks,
/// then the base `Language.getPriorityForId` fallbacks.
pub fn priority_for_id(id: &str) -> i32 {
    if id == "CONFUSIONS2" {
        return 50; // greater than CONFUSIONS
    }
    if id == "RARE_WORDS" {
        return 50;
    }
    if id == "MISSPELLING" {
        return 40;
    }
    if id == "CONFUSIONS" {
        return 40;
    }
    if id == "INCORRECT_EXPRESSIONS" {
        return 40;
    }
    if id == "DIACRITICS" {
        return 30;
    }
    if id.starts_with("ES_SIMPLE_REPLACE_SIMPLE") {
        return 30;
    }
    if id.starts_with("ES_COMPOUNDS") {
        return 50;
    }
    if let Ok(index) = ES_PRIORITIES.binary_search_by(|(key, _)| (*key).cmp(id)) {
        return ES_PRIORITIES[index].1;
    }
    if id.starts_with("AI_ES_HYDRA_LEO") {
        // prefer more specific rules (also speller)
        return -101;
    }
    if id.starts_with("AI_ES_GGEC") {
        // prefer more specific rules (also speller)
        if id == "AI_ES_GGEC_REPLACEMENT_OTHER" {
            return -300;
        }
        return 0;
    }
    if id.starts_with("ES_MULTITOKEN_SPELLING") {
        return -95;
    }
    // base `Language.getPriorityForId`
    if id.eq_ignore_ascii_case("TOO_LONG_SENTENCE") {
        return -101;
    }
    if id == "REPETITIONS_STYLE" {
        return -55;
    }
    if id.contains("STYLE") {
        return -50;
    }
    0
}

/// `Language.getRulePriority` for Spanish. Spanish does not override
/// `getDefaultRulePriorityForStyle`, so the issue-type fallback is 0 (unlike
/// English).
pub fn rule_priority(
    rule_id: &str,
    category_id: &str,
    issue_type: &str,
    rule_priority: i32,
) -> i32 {
    let _ = issue_type;
    let rule_specific = priority_for_id(rule_id);
    if rule_specific != 0 {
        return rule_specific;
    }
    if rule_priority != 0 {
        return rule_priority;
    }
    let category = priority_for_id(category_id);
    if category != 0 {
        return category;
    }
    0
}
"""
    )
    out.append("")

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {args.out}: {len(entries)} entries", file=sys.stderr)


if __name__ == "__main__":
    main()
