#!/usr/bin/env python3
"""Generate crates/lt/src/de/priorities.rs from the pinned Java source.

Reads `German.java` from the LanguageTool checkout and emits the `id2prio`
map (insertion order, commented-out lines skipped) as a Rust static, so the
`CleanOverlappingFilter` German priorities cannot drift from Java.

Usage:
  tools/gen-de-priorities.py [--upstream <lt-checkout>] [--out <file>]
"""

import argparse
import os
import re
import sys

DEFAULT_UPSTREAM = os.environ.get(
    "LT_CHECKOUT",
    os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "languagetool"))
)
JAVA_REL = (
    "languagetool-language-modules/de/src/main/java/org/languagetool/language/"
    "German.java"
)
DEFAULT_OUT = "crates/lt/src/de/priorities.rs"


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", default=DEFAULT_UPSTREAM)
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args()

    java_path = os.path.join(args.upstream, JAVA_REL)
    with open(java_path, encoding="utf-8") as f:
        text = f.read()

    entries = []
    for m in re.finditer(r'id2prio\.put\("([^"]+)",\s*(-?\d+)\);', text):
        line_start = text.rfind("\n", 0, m.start()) + 1
        prefix = text[line_start : m.start()].strip()
        if prefix.startswith("//"):
            continue
        entries.append((m.group(1), int(m.group(2))))

    entries.sort(key=lambda e: e[0])
    out = [
        "// Generated by tools/gen-de-priorities.py from the pinned German.java",
        "// id2prio map — do not edit by hand. The key order is sorted for",
        "// binary search; Java's map lookup is order-independent.",
        "",
        "// entry count: %d" % len(entries),
        "pub(crate) static DE_PRIORITIES: &[(&str, i32)] = &[",
    ]
    for key, value in entries:
        out.append(f"    ({rust_str(key)}, {value}),")
    out.append("];")
    out.append("")
    out.append(
        """
use regex::Regex;
use std::sync::LazyLock;

/// `German.AI_DE_GGEC_MISSING_PUNCT` (`find` semantics, case-insensitive).
static AI_DE_GGEC_MISSING_PUNCT: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(?:AI_DE_GGEC_MISSING_PUNCTUATION_\\d+_DASH_J(_|AE)HRIG|AI_DE_GGEC_REPLACEMENT_CONFUSION)",
    )
    .unwrap()
});

/// `German.getPriorityForId`: explicit map, then the id-prefix fallbacks,
/// then the base `Language.getPriorityForId` fallbacks.
pub fn priority_for_id(id: &str) -> i32 {
    if let Ok(index) = DE_PRIORITIES.binary_search_by(|(key, _)| (*key).cmp(id)) {
        return DE_PRIORITIES[index].1;
    }
    if id.starts_with("DE_PROHIBITED_COMPOUNDS_")
        || id.starts_with("DE_PROHIBITED_COMPOUNDS_PREMIUM_")
    {
        // don't hide spelling mistakes
        return -4;
    }
    if id.starts_with("DE_MULTITOKEN_SPELLING") {
        return -2;
    }
    if id.starts_with("CONFUSION_RULE_") {
        return -1;
    }
    if id.starts_with("AI_DE_HYDRA_LEO") {
        // prefer more specific rules (also speller)
        if id.starts_with("AI_DE_HYDRA_LEO_MISSING_COMMA") {
            return -51; // prefer comma style rules
        }
        if id.starts_with("AI_DE_HYDRA_LEO_CP") {
            return 2;
        }
        if id.starts_with("AI_DE_HYDRA_LEO_DATAKK") {
            return 1;
        }
        return -11;
    }
    if id.starts_with("AI_DE_KOMMA") {
        // prefer comma style rules and AI_DE_HYDRA_LEO_MISSING_COMMA
        return -52;
    }
    if id.starts_with("AI_DE_GGEC") {
        match id {
            // less prio than EMAIL
            "AI_DE_GGEC_MISSING_PUNCTUATION_E_DASH_MAIL" => return 0,
            "AI_DE_GGEC_REPLACEMENT_ADJECTIVE"
            | "AI_DE_GGEC_REPLACEMENT_ADVERB"
            | "AI_DE_GGEC_REPLACEMENT_NOUN"
            | "AI_DE_GGEC_REPLACEMENT_ORTHOGRAPHY_LOWERCASE"
            | "AI_DE_GGEC_REPLACEMENT_ORTHOGRAPHY_SPELL"
            | "AI_DE_GGEC_REPLACEMENT_OTHER"
            | "AI_DE_GGEC_REPLACEMENT_VERB"
            | "AI_DE_GGEC_REPLACEMENT_VERB_FORM"
            | "AI_DE_GGEC_UNNECESSARY_ORTHOGRAPHY_SPACE"
            | "AI_DE_GGEC_UNNECESSARY_OTHER"
            | "AI_DE_GGEC_UNNECESSARY_SPACE" => return -1,
            _ => {}
        }
        if id.starts_with("AI_DE_GGEC_MISSING_ORTHOGRAPHY_SPACE") {
            // lower prio than LT_RECOMMENDATION but higher than speller
            return -2;
        }
        if id.starts_with("AI_DE_GGEC_MISSING_PUNCTUATION_PERIOD") {
            // less prio than spell checker
            return -4;
        }
        if id.starts_with("AI_DE_GGEC_UNNECESSARY_PUNCTUATION") {
            // less prio than FALSCHES_ANFUEHRUNGSZEICHEN
            return -2;
        }
        if AI_DE_GGEC_MISSING_PUNCT.is_match(id) {
            return -1;
        }
        return 1;
    }
    // base `Language.getPriorityForId`
    if id.eq_ignore_ascii_case("TOO_LONG_SENTENCE") {
        return -101;
    }
    if id == "REPETITIONS_STYLE" {
        return -55;
    }
    if id.contains("STYLE") {
        return -50;
    }
    0
}

/// `Language.getRulePriority` for German. German does not override
/// `getDefaultRulePriorityForStyle`, so the issue-type fallback is 0 (unlike
/// English).
pub fn rule_priority(
    rule_id: &str,
    category_id: &str,
    issue_type: &str,
    rule_priority: i32,
) -> i32 {
    let _ = issue_type;
    let rule_specific = priority_for_id(rule_id);
    if rule_specific != 0 {
        return rule_specific;
    }
    if rule_priority != 0 {
        return rule_priority;
    }
    let category = priority_for_id(category_id);
    if category != 0 {
        return category;
    }
    0
}
"""
    )
    out.append("")

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {args.out}: {len(entries)} entries", file=sys.stderr)


if __name__ == "__main__":
    main()
